### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ericnyamu** [jessecooper/EdPurp#1]
Since we are dealing with torrents here is there away (using scripts) to download top 20 torrents(movies)with the highest seed count found on kickasstorrent movie section page found here https://kat.cr/movies/ .
The script should also be able to check  for duplicate movies and also be able to ignore torrents with certain words like cam or spanish (for english speaking people).
    The script could be ran once after three days (using cron job) to scrape the section(movie) and download the top 20 movie torrents by invoking a torrent client of choice.Also if the script could be ran on linux it would be nice.I know its a simple matter of parsing the html file @ kat.cr/movies then scraping for top torrents with user defined setting then invoking a torrent client to download the torrent but i just donot know how to do it programmatically.
Kickasstorrent also have an api @ https://kat.cr/api/ . also this github user has some kickasstorrent api : https://github.com/stephan-mclean/KickassTorrentsAPI and also this one https://github.com/asfaltboy/meowify

**Comment by jessecooper** [comment]
This is possible to do and if I were to do it I would use python (my scripting language of choice), add that to a cron job and use transmission (torrent client) to pick up the torrent files scraped from the site. Though this is out of scope for this project it dose bring up an interesting feature I might add to the site later to just grab the torrent files and add them to the private site. Though this is not a feature I desire if this gets requested as a feature I'll add it as a configuration option.
